### ISSUE TITLE
Error when trying to generate for Solana

### ISSUE THREAD

**Issue by murkai** [thepeanutgalleryandco/create-and-mint-nft-collection#10]
Getting error when trying to generate for Solana. Currently don't have plans to use NFTPort - and just using your repo / code to bypass Blank from being added to metadata. Everything works perfectly when on network.eth but when I change to network.sol I get this error: 

```
eddies-MBP:create-and-mint-nft-collection-1.3.1 eddie$ node index.js
/Users/eddie/Desktop/Solana/create-and-mint-nft-collection-1.3.1/src/main.js:323
  let metadata = metadataList.find((meta) => meta.custom_fields.edition == _editionCount);
                                                                ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at /Users/eddie/Desktop/Solana/create-and-mint-nft-collection-1.3.1/src/main.js:323:65
    at Array.find (<anonymous>)
    at saveMetaDataSingleFile (/Users/eddie/Desktop/Solana/create-and-mint-nft-collection-1.3.1/src/main.js:323:31)
    at /Users/eddie/Desktop/Solana/create-and-mint-nft-collection-1.3.1/src/main.js:418:11
    at async startCreating (/Users/eddie/Desktop/Solana/create-and-mint-nft-collection-1.3.1/src/main.js:383:9)
eddies-MBP:create-and-mint-nft-collection-1.3.1 eddie$
```

Any way to fix? Seems to work okay in the original Hashlips Art Engine repo but get this error in yours. 

Thanks in advance for your help! :)

**Comment by thepeanutgalleryandco** [comment]
@murkai i see where the problem is and will upload a fix in a bit. Do you still have time to wait for the new release or do you require it more urgently?

**Comment by thepeanutgalleryandco** [comment]
@murkai have you had a chance to take a look at the fix?

**Comment by murkai** [comment]
Hi Rohan! Thanks for the fix in advance. Excited to try it out. Hopefully will get a chance to try it out today. Will definitely let you know!

**Comment by thepeanutgalleryandco** [comment]
Any feedback on the issue @murkai ?

**Comment by thepeanutgalleryandco** [comment]
@murkai Hope you are doing well. Any chance you have had a look at this yet?
