### ISSUE TITLE
[FEATURE] Import GIFs as layers

### ISSUE THREAD

**Issue by khangtrn96** [thepeanutgalleryandco/create-and-mint-nft-collection#23]
## Summary

I see Hashlips’project only allow import static images as layers. I hope a feature can import gifs as layers. After that, it will merge gifs and static image together in output file-- Your document is so great. Thanks for your team

**Comment by khangtrn96** [comment]
I have found 2 projects that involve combining gifs together.
Project 1: [https://github.com/Goldo02/gif_art_engine_for_nft.git](url)
Project 2: [https://github.com/dylandev125/nft-gif-generator.git](url)

**Comment by khangtrn96** [comment]
I have just test available layers in Project 2 and it works perfectly. I don't know c++ language, so I can't run Project 1.

**Comment by khangtrn96** [comment]
Sorry I didn't make it clear. First thing I want to combine gif and static images together. Second thing is to output a gif file. in the 2nd project that I tried to run, only the 2nd desired thing was achieved.

**Comment by khangtrn96** [comment]
If there is really a way to do this, it will increase the uniqueness of NFT products.

**Comment by khangtrn96** [comment]
> @khangtrn96 yeah, that is already do-able in the current hashlips repo, but I haven't seen anyone combining the GIF and image layers before. Will do some research as I get time, but I can't promise anything ;)
But I see the difference between Project 2 and Hashlips'project.
Example:
+Hashlips' project is only using for folder structure:
**layers/Eyeball/images**
and
Project 2 is using for folder structure:
**layers/Eyeball/Red/images**
Right?

I want to create GIFs image based on structure **layers/Eyeball/Red/images**, what should I do?

**Comment by thepeanutgalleryandco** [comment]
At the moment, you can create a gif from your collection of images that got generated by npm run build or you can create a gif for every edition that gets generated, that shows how the layers were created put on top of one another to create the image.

In both these options, only png files can be used, like in the repo shared.

**Comment by thepeanutgalleryandco** [comment]
Project 2 adds the possibility of having sub folders in your layers, but he also hard codes his configurations which means it is not actually re-useable and would need to rework it all to make it configurable to have sub folders.

I haven't tried sub folders yet in the Hashlips repo, so it might already be able to work with sub folders. Worth a test.

**Comment by thepeanutgalleryandco** [comment]
@khangtrn96 can you perhaps provide me with a layer folder set that has 3 or 4 layers, with 2 pngs and 2 gifs per layer to test and play around with?

**Comment by khangtrn96** [comment]
[Layer.zip](https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection/files/8073624/Layer.zip)
I hope these are helpful to you.

**Comment by thepeanutgalleryandco** [comment]
@khangtrn96 I have not forgotten about this, the last few weeks was a bit hectic at work and I had some other work to get out first. This is next on my todo list.

**Comment by thepeanutgalleryandco** [comment]
@khangtrn96 i haven't gotten around to this yet, but during my research, I haven't seen how other people do this yet, so will need to do some more research on this topic.

**Comment by thepeanutgalleryandco** [comment]
@khangtrn96 I have researched a bit further, and unfortunately I won't be able to add this functionality into the code base. I don't understand enough of Sprites, GIFs, PNGs, Gid-encoder-2 and Canvas to build this out. If you find anyone that gets this working in their code base, please ping me on this thread again, then I will see if I am able to add it into this code base.

Apologies for not being able to help you out.
