### ISSUE TITLE
[QUESTION] mint item

### ISSUE THREAD

**Issue by stackzwolle** [thepeanutgalleryandco/create-and-mint-nft-collection#37]
hi
can i mint any edition item not starting from 1?

thanks

**Comment by stackzwolle** [comment]
oh nvm got it

thanks

**Comment by thepeanutgalleryandco** [comment]
Four minting options with this code repo:

ERC721
1. Mint - This will mint all items in your ipfsMetas directory.
2. Mint_Item - This will mint the item specified in the account_details.js file.
3. Mint_Range - This will mint all items in between the two numbers specified in the account_details.js file.

ERC1155
5. Mint_Batch - This will mint your items in batch format

Reference - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection#13-minting-nfts
