### ISSUE TITLE
[QUESTION]: deploy contract?

### ISSUE THREAD

**Issue by stackzwolle** [thepeanutgalleryandco/create-and-mint-nft-collection#38]
hi
can i deploy contract with your script? didnt see it in readme file or didnt see any deploy js file in utils/nftport

thanks

**Comment by thepeanutgalleryandco** [comment]
Hi @stackzwolle 

No, I didn't add deploying and updating contract scripts as it seemed to be a bit of a waste of time and is much easier to configure directly on the NFTPort website via (https://docs.nftport.xyz/docs/nftport/b3A6MjE0MDYzNzU-deploy-an-nft-contract and https://docs.nftport.xyz/docs/nftport/b3A6MjU2NTIyMTM-update-a-deployed-contract) OR Collection contracts (https://docs.nftport.xyz/docs/nftport/b3A6Mzk2MjA1MzQ-deploy-an-nft-collection-contract and https://docs.nftport.xyz/docs/nftport/b3A6Mzk2MjA1MzM-update-a-deployed-collection-contract) and then simply saving your request and responses into a text file.

**Comment by thepeanutgalleryandco** [comment]
@stackzwolle just out of curiosity, is there a reason why you would want to be able to do this via a script in your terminal as opposing to the NFTPort website APIs?
