### ISSUE TITLE
[FEATURE] Opensea Polygon Script To Auto Sell NFTs

### ISSUE THREAD

**Issue by thepeanutgalleryandco** [thepeanutgalleryandco/create-and-mint-nft-collection#42]
## Summary

Create a new script that can be used to automate the selling of NFTs for a specific price. As this is the initial script, only need to cater for a single price for all the NFTs that needs to be put up for sale. Script only needs to cater for putting Polygon NFTs up for sale in the initial build.

### Basic example

Add a new script that can take a seed phrase to your wallet that contains the NFTs that needs to be put up for sale, a start edition number, an end edition number, a price and a contract address.

**StartEdition:** 1
**EndEdition:** 10
**Price:** 0.002 (Above $5, as that is the minimum)
**Contract:** 0x09aa1a14e572e6fc05f64e541699d3e0361c7f2f
**Seed Phrase:** one two three mountain lion test four five six big small town

Auto login to Opensea with the Seed phrase for the wallet that owns the NFTs that should be sold. Loop through editions 1 through to 10 (both inclusive) on the contract address and put each NFT up for sale if it can find the NFT edition number and your wallet owns it. Should the items be owned by someone else or the edition can't be found, then skip over to the next edition.

### Motivation

This will allow users to put their NFTs up for sale automatically by simply running a script instead of manually putting each item up for sale.

**Comment by thepeanutgalleryandco** [comment]
This script has been quite tricky to get working 100% as some of the libraries have some issues at times.

A new library called @chainsafe/dappeteer has been introduced. Even though version 2.4.x has been released, I was unable to get the Metamask functionality to work correctly on this. I got the automation to work by using specifically version 2.3.0 (not greater than 2.3.0) along with specifically version 10.1.1 of Metamask. All other version combinations failed in automation testing, so please do not change these versions for the time being, unless the code base receives an update for this.

There's a few configurations that needs to be put in place for this automation script to work, so please update accordingly before running the `npm run sell_nfts` command.

- Update the `constants/account_details.js` file's `contract_address` field with the contract that contains the NFTs that needs to be put up for sale. Also update the `chain` field with the chain that the NFT exists on.

- Update the `utils/opensea/sell_nfts.js` script's fields
    - `START_EDITION` - Set the start edition of the collection where you want to start selling NFTs from.
    - `END_EDITION` - Set the end edition of the collection where you want to stop selling NFTs at.
    - `NFT_PRICE` - Set the price that will be given to each NFT between `START_EDITION` and `END_EDITION`.
    - `seed` field - On line 52 with your own seed phrase or alternatively, keep it as is with 'test' and then when the script runs, simply copy and paste your seed phrase into the seed phrase box in the browser and then click to continue, then the script will proceed. It is up to you. **Please read the warning very carefully within the the `sell_nfts.js` file.**
    - `Opensea URLs` - Please note that the script is catering for Mainnet (Polygon), as it is looking at the Opensea production URL. If you need to run tests against Testnet (Rinkeby), then update lines 73 and 78 to `testnets.opensea.io` instead of `opensea.io`.

**Comment by thepeanutgalleryandco** [comment]
Added a new script `utils/opensea/sell_nfts.js` script that allows for putting NFTs up for sale in an automated way.

**Comment by thepeanutgalleryandco** [comment]
Tests have been run against ERC721 contract on Polygon network. Not 100% sure if this will work with ERC1155, especially if token count is also an option. If this is needed, then users can raise a ticket for an enhancement of this feature.

**Comment by thepeanutgalleryandco** [comment]
Chainsafe Github - https://github.com/ChainSafe/dappeteer

**Comment by thepeanutgalleryandco** [comment]
Please note that sometimes, when running the script for the first time, it struggles to download the metamask version. What you will experience is that the script merely finishes, without anything happening. Simply run the script again. On the 2nd or 3rd time, the metamask download will succeed and from there, the script should work every time.

**Comment by thepeanutgalleryandco** [comment]
Please remember to unlock the collection for selling by putting an item up for sale initially and paying the unlocking fee, otherwise the script won't work.

**Comment by d-3-v-s-k-i** [comment]
> ## Summary
> 
> Create a new script that can be used to automate the selling of NFTs for a specific price. As this is the initial script, only need to cater for a single price for all the NFTs that needs to be put up for sale. Script only needs to cater for putting Polygon NFTs up for sale in the initial build.
> 
> ### Basic example
> 
> Add a new script that can take a seed phrase to your wallet that contains the NFTs that needs to be put up for sale, a start edition number, an end edition number, a price and a contract address.
> 
> **StartEdition:** 1
>[ **EndEdition:** 10
> **Price:** 0.002 (Above $5, as that is the minimum)
> **Contract:** 0x09aa1a14e572e6fc05f64e541699d3e0361c7f2f
- [ ] - > **Seed Phrase:** one two ]()@razielll three mountain lion test four five six big small town
> 
> Auto login to Opensea with the Seed phrase for the wallet that owns the NFTs that should be sold. Loop through editions 1 through to 10 (both inclusive) on the contract address and put each NFT up for sale if it can find the NFT edition number and your wallet owns it. Should the items be owned by someone else or the edition can't be found, then skip over to the next edition.
> 
> ### Motivation
> 
> This will allow users to put their NFTs up for sale automatically by simply running a script instead of manually putting each item up for sale.
>
