### ISSUE TITLE
[QUESTION]Layer Combination Exclusions Not working

### ISSUE THREAD

**Issue by 7Fpuf** [thepeanutgalleryandco/create-and-mint-nft-collection#46]
## Summary
Hello, 

I am very new to coding and am having trouble with the incompatibleTraits feature. It doesn't seem to be working. Is there something I need to do before running?

**Comment by 7Fpuf** [comment]
It is telling me that the combinations are being filtered but they are not.
![Screen Shot 2022-04-03 at 12 38 17 PM](https://user-images.githubusercontent.com/102917217/161441097-b40cad73-b5a0-4235-a8c8-c892d70b9e69.png)
![Screen Shot 2022-04-03 at 12 38 29 PM](https://user-images.githubusercontent.com/102917217/161441098-bb45f12e-d9b7-4c1e-847e-533962931425.png)

**Comment by thepeanutgalleryandco** [comment]
Hi @7Fpuf 

Can you share the metadata for the file nft edition and image that you are saying the filtration is not working?

**Comment by 7Fpuf** [comment]
Is this what you are asking for? Also would you be open to jumping on a call with me on discord? I've been trying to get it to work for 3 days now.

![Screen Shot 2022-04-03 at 2 04 28 PM](https://user-images.githubusercontent.com/102917217/161443967-0641105e-18d2-4fd2-a07e-05dda1c17768.png)
![Screen Shot 2022-04-03 at 2 03 41 PM](https://user-images.githubusercontent.com/102917217/161443970-07173ba5-06c1-4888-8c26-446f54a76986.png)

**Comment by thepeanutgalleryandco** [comment]
@7Fpuf - Please add me - ThePeanutGalleryAndCo#9888

**Comment by 7Fpuf** [comment]
@thepeanutgalleryandco I just did. Thank you for the quick response

**Comment by Moonnaac** [comment]
Hello! This is the exact same thing is happening to me! How did you fixed it? @7Fpuf Thanks in advance!

**Comment by thepeanutgalleryandco** [comment]
@Moonnaac the user had two files with the same content. For example 'Smoker Face.png' and 'New Face.png' in the face layer. The user kept seeing the Smoker face and then after checking the metadata and reviewing the files, saw that the New face has the same image as Smoker face. Either both need to filter or the duplicate should be removed.
