### ISSUE TITLE
[BUG] Error: No node found for selector: div[aria-hidden="false"]

### ISSUE THREAD

**Issue by WFamilyNFT** [thepeanutgalleryandco/create-and-mint-nft-collection#58]
## Description

I'm trying to sell, but I get the following error: No node found for selector: div[aria-hidden="false"]

Can anyone help?

**Comment by thepeanutgalleryandco** [comment]
Hi @WFamilyNFT .

Please confirm the steps were followed:

1. Download repo
2. Extract repo
3. Run npm install
4. Update account_details.js with the correct contract_address and chain (only polygon works)
5. Minted the nfts to yourself as you can only put your own items up for sale
6. Downloaded metamask v10.1.1 as per the feature ticket.
7. Update the sell_nfts.js with your sale info and your private key.

**Comment by thepeanutgalleryandco** [comment]
Please share your contract address and chain that you are using as well.

**Comment by thepeanutgalleryandco** [comment]
@WFamilyNFT any update?

**Comment by thepeanutgalleryandco** [comment]
Closing this bug for now. Please re-open if still an issue.
