### ISSUE TITLE
[QUESTION] Why 'layerItemsMaxRepeatedTraits' don't work?

### ISSUE THREAD

**Issue by bettyboomy** [thepeanutgalleryandco/create-and-mint-nft-collection#59]
Hello guys!

Thanks a lot for your amazing code!

Im trying to use 'layerItemsMaxRepeatedTraits' because I want each item from "hat" layer to repeat only once.

This is my code:

![doubt](https://user-images.githubusercontent.com/101867301/162696100-ffbe6cea-ecf8-4285-8711-05d26538bb21.png)

It doesn't work for me, the "hat" layer items keep repeating more than once.

Does anyone know why?

Thanks in advance.

BR

Betty

**Comment by thepeanutgalleryandco** [comment]
Hi @bettyboomy 

Hope you are doing well! Please see example below.

`maxRepeatedTraits` that sits on a global level states that any layer can only be used X number of times.
`maxRepeatedTrait` that sits on a layer level states that the specific layer can only be used Y number of times. This does not mean each layer item in the layer, it means the layer as a whole.
`layerItemMaxRepeatedTrait` that sits on a layer item level states that the specific layer item can only be used Z number times.

From your configuration, you are only specifying the layer name, and you need to add the layer item as well. If you want to add repeatability of each layer item for a layer, then it would look something like this.
`
layerItemsMaxRepeatedTraits: [
      { name: "hat/test", layerItemMaxRepeatedTrait: 1 },
      { name: "hat/test2", layerItemMaxRepeatedTrait: 1 },
      { name: "hat/test3", layerItemMaxRepeatedTrait: 1 }
    ]
`

**Example:**
const layerConfigurations = [
  {
    growEditionSizeTo: 2,
    maxRepeatedTraits: 1,
    layersOrder: [
      { name: "Background" },
      { name: "Eyeball" },
      { name: "Eye color", maxRepeatedTrait: 2 },
      { name: "Iris" },
      { name: "Shine" },
      { name: "Bottom lid", maxRepeatedTrait: 3 },
      { name: "Top lid" },
    ],
    layerItemsMaxRepeatedTraits: [
      { name: "Background/Black", layerItemMaxRepeatedTrait: 4 },
      { name: "Eyeball/Red", layerItemMaxRepeatedTrait: 5 }
    ],
    incompatibleTraits: {
      "Eye color/Cyan": [
        "Eyeball/Red",
      ],
      "Iris/Large": [
        "Bottom lid/High",
        "Top lid/High"
      ],
    },
    dependentTraits: {
      "Eye color/Cyan": [
        "Eyeball/White",
      ],
      "Background/Blue": [
        "Eyeball/Red",
        "Top lid/low"
      ],
    }
  },
];
