### ISSUE TITLE
[FEATURE] Add Maximum Repeatability For All Items In A Layer In A Single Configuration

### ISSUE THREAD

**Issue by thepeanutgalleryandco** [thepeanutgalleryandco/create-and-mint-nft-collection#65]
## Summary

Add the ability to specify the maximum repeatability for all items in a layer. At the moment, only the layer's repeatability can be set.

### Basic example

Layer X with 10 layer items.
Each layer item should generate a maximum of 2 times.
Grow edition size to 20.
Set the maximum repeatability of layer X to 2.

20 Images should be generated with each layer X item only added twice. Any other generated attempts with the layer X item should be discarded and added to the fail count as the maximum repeatability has been reached.

### Motivation

Instead of adding a maximum repeatability of 2 for each of layer X's items, the repeatability can be set once off for all layer items.

**Comment by marcneagu** [comment]
Tried it, and it works like a charm! 
If I have 90 layer items in "body 3" layer and I want no duplicates, here is my config:

const layerConfigurations = [
  {
    growEditionSizeTo: 90,
    layersOrder: [
  { name: "Background" },
  { name: "Body 3", options: { displayName: "Body", }, layerItemsMaxRepeatedTrait: 1 },
  { name: "Hair" },
  { name: "Hat" },
  { name: "Beard" },
  { name: "Glasses Special", options: { displayName: "Glasses", }, },
  ],
},
];

No need to specify each layerItem (png) in every single layer (folder).
I appreciate your work, thank you!
