### ISSUE TITLE
[BUG]Error: No node found for selector: div[aria-hidden="false"] when attempting to put edition on sale: 9995

### ISSUE THREAD

**Issue by Undoqaq** [thepeanutgalleryandco/create-and-mint-nft-collection#68]
This script runs until the price and date are entered, then the complete listing is not clicked, Also did not sign the message to metamask.

**Comment by thepeanutgalleryandco** [comment]
@Undoqaq which script are you trying to use? The sell_nfts script? Can you please share your contract address that you are trying to use.

**Comment by Undoqaq** [comment]
> @Undoqaq which script are you trying to use? The sell_nfts script? Can you please share your contract address that you are trying to use.

Yeah it's sell_nfts, Here is my contract address "0xB19Ad0c39b28576EC95FfF0920909D0B09669797".

**Comment by Undoqaq** [comment]
> @Undoqaq谢谢，您能否确认您尝试使用的销售配置。请提供以下所有值。
> 
> ![截图_20220524-193539_Chrome](https://user-images.githubusercontent.com/52892685/170097745-6910e1eb-3549-4556-86c0-e46070023a23.jpg)

@thepeanutgalleryandco 
<img width="269" alt="data" src="https://user-images.githubusercontent.com/105921740/170105066-e41614a8-2374-4d0f-8cbb-c3ea621e6db3.png">

**Comment by Undoqaq** [comment]
> @Undoqaq thanks, can you also confirm the selling configuration that you are trying to use. All of the below values please.
> 
> ![Screenshot_20220524-193539_Chrome](https://user-images.githubusercontent.com/52892685/170097745-6910e1eb-3549-4556-86c0-e46070023a23.jpg)

@thepeanutgalleryandco 
<img width="283" alt="截屏2022-05-25 02 23 32" src="https://user-images.githubusercontent.com/105921740/170105943-db97a0c7-366d-4059-a257-4c44435feadd.png">

**Comment by thepeanutgalleryandco** [comment]
@Undoqaq I just ran the same the following code piece and successfully put my NFTs up for sale. Take careful note of the start hour and minute along with end hour and minute. You can't list an item with a start hour and minute that is earlier than today as it lists the item from the current timestamp. I suspect your start and end hours caused issues. Also, it is not 0, it will be 00 for hour and 00 for minute as well. It is in 24-hour format.

I also noted that I had a few issues with dappeteer version, metamask version and puppeteer.
My latest test ran on the following:
- Metamask: v10.8.1 (Instead of v10.1.1)
- @chainsafe/dappeteer: 2.4.1 (Instead of 2.3.0)
- puppeteer: 13.7.0 (Instead of 13.5.0)

In my next update, I will update the base versions as well.

[Latest listed items with script](https://opensea.io/collection/steak-bites?search[sortAscending]=false&search[sortBy]=LISTING_DATE)

````
const START_EDITION = 9992; 
const END_EDITION = 9995; 
const NFT_PRICE = 0.01; 
const DROPDOWN_OPTION = 6; 
const DATE_PICK_SKIP = 7; 
const START_HOUR = 23; 
const START_MINUTE = 00; 
const END_HOUR = 23; 
const END_MINUTE = 59;
````

**Comment by Undoqaq** [comment]
> @Undoqaq I just ran the same the following code piece and successfully put my NFTs up for sale. Take careful note of the start hour and minute along with end hour and minute. You can't list an item with a start hour and minute that is earlier than today as it lists the item from the current timestamp. I suspect your start and end hours caused issues. Also, it is not 0, it will be 00 for hour and 00 for minute as well. It is in 24-hour format.
> 
> I also noted that I had a few issues with dappeteer version, metamask version and puppeteer. My latest test ran on the following:
> 
> * Metamask: v10.8.1 (Instead of v10.1.1)
> * @chainsafe/dappeteer: 2.4.1 (Instead of 2.3.0)
> * puppeteer: 13.7.0 (Instead of 13.5.0)
> 
> In my next update, I will update the base versions as well.
> 
> [Latest listed items with script](https://opensea.io/collection/steak-bites?search%5BsortAscending%5D=false&search%5BsortBy%5D=LISTING_DATE)
> 
> ```
> const START_EDITION = 9992; 
> const END_EDITION = 9995; 
> const NFT_PRICE = 0.01; 
> const DROPDOWN_OPTION = 6; 
> const DATE_PICK_SKIP = 7; 
> const START_HOUR = 23; 
> const START_MINUTE = 00; 
> const END_HOUR = 23; 
> const END_MINUTE = 59;
> ```

Thanks for your answer. I guess start and end hours shouldn't be the problem. Because I also encountered this problem when I filled in 23 00 before. I actually want the start and end hours to be the current latest default time at the time of sale.  So I set the start and end time to 00. But I'll check the version and try to run successfully. Thanks again for your answer.

**Comment by thepeanutgalleryandco** [comment]
Maybe test to put a single item up for sale with the time in the future, like my example, and see if you can get it up for sale.

**Comment by Undoqaq** [comment]
@thepeanutgalleryandco Good news! I solved it, no relation to version and start end hour. Just need to change the code  ”await page.keyboard.press('Tab', { page });” in sell_nfts.js to “await page.keyboard.press('Enter', { page });”. I don't know why my computer can't use “Tab” to exit the date picker. But it works with Enter. Also my start and end hours are still 0, and the sale is successful. Thanks for your help.                                       
                                                                                                                                                                         PS:My computer is mac
Old:
<img width="640" alt="old" src="https://user-images.githubusercontent.com/105921740/170272811-e0bc7b39-d579-41fc-a38a-419128299d15.png">
New:
<img width="657" alt="new" src="https://user-images.githubusercontent.com/105921740/170272861-c7a6797a-c69c-4d78-96b1-96eca76311ed.png">

**Comment by thepeanutgalleryandco** [comment]
That is very interesting, I am using a mac as well @Undoqaq , and tab works without issues on my end to move between the settings.

**Comment by Undoqaq** [comment]
@thepeanutgalleryandco If you're also using a mac, that's really weird. But I do currently use enter and it works. And a new question, in the process of selling, occasionally a few NFTs will fail. Maybe 4-5 out of 100, and I think it must be my network problem.
