### ISSUE TITLE
[QUESTION] How to create multiple template types in a single collection?

### ISSUE THREAD

**Issue by Artyana** [thepeanutgalleryandco/create-and-mint-nft-collection#74]
## Summary

Hello!

The template provides a simple way to match layers you’d like to see together or turn off certain layers for some portion of your tokens.
How to create multiple template types in a single collection?

Thank you.

**Comment by thepeanutgalleryandco** [comment]
The layerconfiguration in the config.js is an array. You can check the original codebase of Hashlips on how to use multiple configuration sets to build an entire collection.

Basically something like the below would use 3 different config sets and make a total of 10 nfts.

const layerConfigurations = [
 { growEditionSizeTo: 3, layersOrder: [ { name: "Background" }, { name: "Eyeball" }, { name: "Eye color" }, { name: "Iris" }, { name: "Shine" }, { name: "Bottom lid" }, { name: "Top lid" } ] },
{ growEditionSizeTo: 5, layersOrder: [ { name: "Background" }, { name: "Eyeball" }, { name: "Eye color" }, { name: "Iris" }, { name: "Shine" }, { name: "Bottom lid" } ] },
{ growEditionSizeTo: 10, layersOrder: [ { name: "Background" }, { name: "Eye color" }, { name: "Iris" }, { name: "Shine" }, { name: "Top lid" }, ] }
];
